lang: fa_IR
source: src
title: مهدی صادقی
motto: در مورد نرم‌افزار و ایده‌هایم
author: مهدی صادقی
email: mehdi@mehdix.ir
baseurl: ""
url: https://mehdix.ir
keywords: کامپیوتر برنامه‌نویسی پایتون تکنولوژی مهندسی ایران وب
copyright: Commons Attribution 4.0 International
description: >
  سکوی انتشار مطالبی در مورد دانش تولید نرم‌افزار و ایده‌ها و علایق شخصی‌ام.

long_description: >
  بچه که بودیم همیشه برای بازی خونه می‌ساختیم. حالا هم نمونه‌اش رو در وب ساختم.
  اینجا سکوی انتشار مطالبی در مورد دانش تولید نرم‌افزار و ایده‌ها و علایق شخصی‌ام است،
  بویژه راه‌حل‌های مهندسی که باعث رشد و پیشرفتم شده است و می‌تواند مورد استفاده دیگران هم قرار بگیرد.

github:
  username: mehdisadeghi
  repository: mehdix.ir
favicon: assets/img/me.png
avatar: assets/img/me.png

permalink: :title:output_ext
timezone: Europe/Berlin

paginate: 20
paginate_path: /page:num/

collections:
  projects:
    output: true

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
- scope:
    path: ""
    type: "projects"
  values:
    layout: "project"
