service: mehdix-commentz

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}

functions:
  notify:
    handler: send-mail/send-mail.handler
    name: ${self:provider.stage}-notify
    package:
      include:
        - send-mail/**
    events:
      - http:
          path: notify
          method: post
          cors: true
