- bucket: !!binary |
    Z0FBQUFBQmFaSmV4ZVF1aDJnV0o3Qm83ajlSa3VUelRNM2F3a3laZEEzWlRveVliRUQyZlp4X016
    ODF3MS1HdlBTUHZUeHJ4SzVaSVR0TTRGaDdLdEFQWVZPYkR5Rzd0UVdVMW5KSHY2UzFNY2J0eW9r
    YnlDSGs9
  created_at: '2018-01-03T10:55:42.854Z'
  email: 27b6f3ebc1535b4b11b1508ec7c7364c
  id: 5a4cb6ae8df9df36f12c16c5
  message: من یه دامنه و هاست دارم که به هم متصل بودن، تصورم این بود که میشه مثل CloudFlare
    این Netlify رو بین این دو قرار بدم، وارد Netlify شدم و دامنم رو به DNS Zone اضافه
    کردم، چهار تا NameServer داد که دامنم روی اونا تنظیم کردم، بعد تو Netlify اومدم
    توی قسمت DNS Records دو تا NameServer هاستم رو در قالب  NS وارد کردم، الان بعد
    یه روز دامنم به هاست متصل نمیشه. نمیدونم ایراد کارم کجاست؟
  name: روح اله
  page_id: /netlify
  reply_to: null
  website: ''
- bucket: !!binary |
    Z0FBQUFBQmFaSmV4S3hsd1ctRDh3NWp4OWVQTkd3VjZuajlYQ1l5MHNBd3FGUWhrMFJrRDNnMWVH
    VFJtcXN6YXdmQmdPZktiWlluUE1zd0dzbU51R1Q4MUFsb3k2UzU3MFE5UzNzd29fSURBLVMzaHlL
    cXlRLU09
  created_at: '2018-01-03T15:39:47.386Z'
  email: 0371f5b900b484368f9e1717d7d965b1
  id: 5a4cf9438df9df223b2c16c9
  message: "> تصورم این بود که میشه مثل CloudFlare این Netlify رو بین این دو قرار\
    \ بدم\r\n\r\nنتلیفای سایت دیگه‌ای رو نمی‌تونه سرو کنه. همه چیز باید رو خودش باشه.\
    \ مناسب سایتهای استاتیکه.\r\n\r\n> بعد تو Netlify اومدم توی قسمت DNS Records دو\
    \ تا NameServer هاستم رو در قالب NS وارد کردم\r\n\r\nاین قسمت فقط به درد تعریف\
    \ رکوردهای جدید می‌خوره. مثلا تعریف زیر دامنه برای ایمیل. نمی‌تونی هاستت خودت\
    \ رو اینجا وارد کنی.\r\n\r\nکلا نمی‌تونی از نتلیفای برای اضافه کردن https به سرور\
    \ یا هاست شخصی خودت استفاده کنی مگر اینکه استاتیک باشه و کاملا از روی نتلیفای\
    \ سرو بشه. مطلب رو اصلاح می‌کنم که باعث سردرگمی نشه."
  name: مهدی صادقی
  page_id: /netlify
  reply_to: null
  website: https://mehdix.ir
- bucket: !!binary |
    Z0FBQUFBQmdwOWxaLU50anFxMjNzUG14T2xNa2Foa3pPSjlLRnc3bGdDSWlJdTRtWG5DVmdZX282
    dmFsMzYzTmxuckxOLWxnZGdZMm5SQnBFRVRyM0VZbFg2STlIUDVybFhzM2JsaW1aNXFGOHFIb3BX
    c0pscmM9
  created_at: '2019-09-19T23:04:42.704Z'
  email: 0371f5b900b484368f9e1717d7d965b1
  id: 5d84098ae1148f18864b710a
  message: "من تا حالا از NS استفاده نکردم. من تنها در رجیستری دامنه خودم آدرس نیم‌سرورهای\
    \ نتلیفای رو دادم و در نتلیفای هم دامنه‌ام رو اضافه کردم و کار کرد. عکس تنظیماتش\
    \ رو [اینجا](https://mehdix.org/~mx/netlifydns.png) ببین.\r\n\r\n![test](https://mehdix.org/~mx/netlifydns.png)"
  name: وبلاگ‌صاحاب
  page_id: /netlify
  reply_to: 5a4cb6ae8df9df36f12c16c5
  website: ''
- bucket: !!binary |
    Z0FBQUFBQmdwOWxaWUMtMWpvT1BLZFV1RXVaYVFWY3I3RHBUcEJZM2toWlV6NE5leFVCMmxsUzdZ
    OENYaW42aTJFOHc5V0pLY0ljMDRFcVBHNWZMRXAyYVBWd0N3Z0R3ZnFMZUZ0YVQzb2hHNWZhbjRG
    aTEwSWs9
  created_at: '2019-09-19T23:12:58.226Z'
  email: 0371f5b900b484368f9e1717d7d965b1
  id: 5d840b7aec74166bd0db6a26
  message: ممکنه اسم دامنه‌ات تو ایران فیلتر شده باشه ولی IPش نه.
  name: وبلاگ‌صاحاب
  page_id: /netlify
  reply_to: 5d83a84c2d8d1af701b1c204
  website: ''
- bucket: !!binary |
    Z0FBQUFBQmdwOWxadldsRUhNMXo5d3ZKS1NtZ3Z3RUxDbFE0OUtzUkd2Y1hLLUU5UDJ4b295UXZm
    ZkVFczBLdVZkcmI5eEJ6N0JubXFMelpWOERzVlNMSTdRdkZKTGJodnc9PQ==
  created_at: '2021-01-24T08:07:26.695Z'
  email: 1188dce949020d94a897f2633434799c
  id: 600d2abebb458b7d17c7e5d0
  message: "متاسفانه دسترسی به سرویس app در netlify تو ایران بسته شده و بدون فیلترشکن\
    \ به سایتت دسترسی نداریم.\U0001F614\r\n"
  name: محمد
  page_id: netlify
  reply_to: ''
  website: https://zmim.ir
- bucket: !!binary |
    Z0FBQUFBQmdwOWxaZVRrWkxVOThWcWpFbW93UjJOQW5VTWhWMG03QjEwSVRfMG5TeVFKVVkyRGZa
    Z1hmd09iOHVOT3QwN2NXRE9Obno5VW4wY2dRcm5NV0lvMUJOZ05BZEd4NXlOWV9uR0F3a1lkRWtf
    c3p6bWM9
  created_at: '2021-01-24T10:19:24.958Z'
  email: 0371f5b900b484368f9e1717d7d965b1
  id: 600d49acb96e7e7f703ddbc1
  message: ممنون که اطلاع دادی. البته تا حدودی قابل پیش‌بینی بود. بهرحال هر چیز بدردبخوری
    یا از داخل فیلتر می‌شه یا از خارج. البته من بی‌خبر از این اوضاع در تدارک مهاجرت
    به سرور سلف‌هاست خودم بودم، حالا سریع‌تر انجامش می‌دم.
  name: مهدی
  page_id: netlify
  reply_to: 600d2abebb458b7d17c7e5d0
  website: https://mehdix.ir
